Repository reznikovkg/pedigree, pull requests merged in 2024-02, with the labels that each got.

#18 PersonCard
  vue/src/components/cards/PersonCard.vue
  vue/src/components/pages/Home.vue
Labels: invalid

#25 8
  package-lock.json
  vue/package.json
  vue/src/components/App.vue
  vue/src/main.js
Labels: errors, invalid

#20 Плотников, Карцев #17
  vue/src/components/forms/WeddingForms.vue
  vue/src/components/pages/Home.vue
Labels: errors, invalid

#32 #6 PersonForm
  vue/src/components/forms/EducationForm.vue
  vue/src/components/forms/PersonForm.vue
  vue/src/components/pages/Home.vue
Labels: errors, invalid

#39 Дворецков #33
  vue/src/components/forms/MilitaryForm.vue
  vue/src/components/pages/Home.vue
Labels: errors, invalid

#41 #34 Updated EducationForm
  vue/src/components/forms/EducationForm.vue
  vue/src/components/pages/Home.vue
Labels: errors

#23 Будиловский, Смирнов, создать компонент превью карточки человека #5
  vue/src/components/cards/PersonPreviewCard.vue
Labels: errors

#42 #13 Settings module
  vue/src/main.js
  vue/src/mixins/settings.js
  vue/src/store/index.js
  vue/src/store/settings.js
Labels: errors

#46 Описать объект Person на TypeScript #36
  vue/src/types/person.ts
Labels: errors, invalid
